Repository jmlawrence/LeetCode-Solutions-in-JS-and-TS, pull requests merged in 2022-10, with the labels that each got.

#2 LeetCode#1832: JS check if sentence is a pangram & LeetCode#2011
  JS/Check If Senctence Is Pangram.js
  JS/Final Value of Variable After Performing Operation.js
Labels: Fresh

#1 improvement: add some more comments and cleanup variable names
  JS/String Compression II.js
Labels: Improvement

#3 new: implement JS remove element algo
  JS/27. Remove Element.js
Labels: New

#6 improvement: rename Two Sum
  JS/1. Two Sum.js
Labels: Improvement

#4 Implement 8 - String to Integer
  JS/8. String to Integer (atoi).js
Labels: New

#5 new: JS - 10. Regular Expression Matching
  JS/10. Regular Expression Matching.js
Labels: New

#7 new: js + py solution for 38
  JS/38. Count and Say.js
  Python/38. Count and Say.py
Labels: New

#9 improvement: naming and cleanup
  JS/102. Binary Tree Level Order Traversal.js
  JS/105. Construct Binary Tree from Preorder and Inorder Traversal.js
  JS/1108. Defanging an IP Address.js
  JS/124. Binary Tree Maximum Path Sum.js
  JS/125. Valid Palindrome.js
  JS/133. Clone Graph.js
  JS/139. Word Break.js
  JS/15. 3Sum.js
  JS/16. 3Sum Closest.js
  JS/18. 4Sum.js
  JS/1832. Check if Sentence is Pangram.js
  JS/1929. Concatenation of Array.js
  JS/2. Add Two Numbers.js
  JS/2235. Add Two Integers
  JS/23. Merge k Sorted Lists.js
  JS/269. Alien Dictionary.js
  JS/297. Serialize and Deserialize Binary Tree.js
  JS/3. Longest Substring Without Repeating Characters.js
  JS/322. Coin Change.js
  JS/33. Search in Rotated Sorted Array.js
  JS/338. Counting Bits.js
  JS/347. Top K Frequent Elements.js
  JS/39. Combination Sum.js
  JS/4. Median of Two Sorted Arrays.js
  JS/5. Longest Palindromic Substring.js
  JS/54. Spiral Matrix.js
  JS/572. Subtree of Another Tree.js
  JS/6. Zigzag Conversion.js
  JS/62. Unique Paths.js
  JS/647. Palindromic Substrings.js
  JS/653. Two Sum IV - Input is a BST.js
  JS/7. Reverse Integer.js
  JS/70. Climbing Stairs.js
  JS/76. Minimum Window Substring.js
  JS/88. Merge Sorted Array.js
  JS/9. Palindrome Number.js
  JS/91. Decode Ways.js
  JS/98. Validate Binary Search Tree.js
  JS/Check If Senctence Is Pangram.js
  JS/Clone Graph.js
  JS/Coin Change.js
  JS/Merge Sorted Array.js
  JS/Search in Rotated Sorted Array.js
  JS/Validate Binary Search Tree.js
  Python/88. Merge Sorted Array.py
  TS/7. Reverse Integer.ts
Labels: Improvement, New

#12 new: 35 in JS and Python
  JS/12. Integer to Roman.js
  JS/2011. Final Value of Variable After Performing Operations.js
  JS/207. Course Schedule.js
  JS/2095. Delete the Middle Node of a Linked List.js
  JS/2235. Add Two Integers.js
  JS/271. Encode and Decode Strings.js
  JS/35. Search Insert Position.js
  JS/57. Insert Interval .js
  JS/Course Schedule.js
  JS/Final Value of Variable After Performing Operation.js
  Python/35. Search Insert Position.py
Labels: Improvement, New

#13 new: js + py - 66. Plus One
  JS/66. Plus One.js
  Python/66. Plus One.py
Labels: New

#15 LeetCode#645: Iterative Javascript
  JS/645. Set Mismatch.js
Labels: New

#14 new: JS + PY: 219
  JS/219. Contains Duplicate II.js
  Python/219. Contains Duplicate II.py
Labels: New

#17 new: JS + Python - 83
  JS/83. Remove Duplicates from Sorted List.js
  Python/83. Remove Duplicates from Sorted List.py
Labels: New

#18 new: JS - Implement 118
  JS/118. Pascal's Triangle.js
Labels: documentation, New

#19 Simplify and clean up reverseBits.
  JS/190. Reverse Bits.js
Labels: Improvement

#20 Simplify 13. Roman to Integer
  JS/13. Roman to Integer.js
Labels: Improvement

#21 LeetCode#1662: simple one liner
  JS/1662. Check If Two String Arrays are Equivalent.js
Labels: New

#22 new: Add in JS and Python solutions for 30 (and Python solution for 1662
  JS/30. Substring with Concatenation of All Words.js
  Python/1662. Check If Two String Arrays are Equivalent.py
  Python/30. Substring with Concatenation of All Words.py
Labels: New
